---
apiVersion: v1
kind: Namespace
metadata:
  name: wellness-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wellness-front
  namespace: wellness-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wellness-front
  template:
    metadata:
      labels:
        app: wellness-front
    spec:
      containers:
      - name: wellness-front
        image: amdaziz/wellness-front:<TAG>
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  namespace: wellness-ns
  labels:
    app: wellness-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30009
  selector:
    app: wellness-front